# Generated by Django 4.1.2 on 2022-10-20 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
